version: '3.8'

networks:
  keycloak-network:
    driver: bridge

services:

  db:
    image: postgres:latest
    container_name: keycloak-db
    restart: unless-stopped
    env_file: postgres.env 
    ports:
      - '5432:5432'
    networks:
      - keycloak-network

  keycloak:
    container_name: keycloak
    image: quay.io/keycloak/keycloak:latest
    restart: unless-stopped
    entrypoint: /opt/keycloak/bin/kc.sh start-dev
    ports:
      - 8080:8080
      - 8443:8443
    env_file: keycloak.env 
    healthcheck:
      test:
        ["CMD-SHELL", "curl -f http://localhost:8080/ || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 5  
    networks:
      - keycloak-network
    depends_on:
      - db

