org: yatsserverless
app: server-less-rest-api
service: server-less-rest-api
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs14.x

functions:
  myTestFunction:
    handler: server-less-rest-api/index.myTestFunction
    events:
      - http:
          path: /path
          method: get
          cors: true

plugins:
  - serverless-offline
